Plugin:
  UpdateCheckOnJoin: true
  language: english
  Currency: $

# yml or MySQL
Storage: yml

BungeeCord:
  Enable: false
  thisServer: 'Server'

GUI:
  DefaultGUI: default

UseItem:
  Enable: true
  AllowToggle: true
  Join:
    GiveOnEveryJoin: true
    GiveOnFirstJoin: false
    Cursor:
      ToGUIItem:
        OnLogin: true
        OnFirstLogin: true
        ServerChange: false
  BlockMoveAndDrop: true
  OpenGUI: default
  Permission:
    # Permission: commandgui.useitem.gui
    NeededToUse: true
  InventorySlot:
    FreeSlot: false
    SlotEnforce: false
    Slot: 1
  Item:
    Material: Paper
    PlayerHead:
      Enable: false
      PlayerWhoHasOpenedTheGUI: false
      PlayerName: ''
  Name: '&bDefault &6GUI'
  Lore:
    - '&eOpen the GUI from &bBuilders-Paradise'

