Plugin:
  VaultNotSetUp: '[prefix] &4Vault / Economy not set up!'
  SoundNotFound: '[prefix] &4The sound &6[sound] &4was not found! Please check the
    settings.'
  OnlyForPlayer: '[prefix] &cThis command is for players only!'
  DefaultGUI:
    create: '[prefix] &2DefaultGUI was created. You can find it in the directory::
      &e[directory]&2!'
  Reload:
    Start: '[prefix] &6Plugin is reloaded...'
    End: '[prefix] &2Plugin was successfully reloaded.'
    Warning: '[prefix] &6To enable / disable alias commands, reload / restart the
      server!'
NoPermission:
  ForCommandGUI: '[prefix] &cYou do not have permission for &4Command&9GUI&c!'
  ForCommand: '[prefix] &cFor &b[cmd] &cyou lack the permission &6[perm]&c!'
  ForUseItem: '[prefix] &cYou lack the permission &6[perm] &cto use the item for the
    GUI: &6[gui].'
  ForItem: '[prefix] &cFor &b[item] &cyou lack the permission &6[perm]&c!'
UseItem:
  UseItem_ON: '[prefix] &2You have activated the GUI item.'
  UseItem_OFF: '[prefix] &2You have disabled the GUI item.'
  Change_Slot: '[prefix] &2You have changed the GUI item to slot: &6[slot]&2.'
  SlotNotEmpty: '[prefix] &6The slot &e[slot] &6is currently occupied!'
  SlotAlreadySet: '[prefix] &6The slot ยงe[slot] ยง6is already set!'
  ItemSlot_wrongValue: '[prefix] &cThe specified slot must be between 1 and 9!'
Cost:
  Buy_msg: '[prefix] &2You bought [itemname] &2for &6[price]&2.'
  No_money: '[prefix] &cYou don''t have enough money!'
  NoInventorySpace: '[prefix] &cYou have no room in your inventory!'
ServerChange:
  onServerChange: '[prefix] &2You will be connected to the server &e[server]ยง2.'
GUI:
  GUInotFound: '[prefix] &cThe GUI chosen by the does not exist.'
  GUIisDisabled: '[prefix] &cThe GUI [gui] &cis currently Disabled!'
Give:
  Sender: '[prefix] &2You have given &6[player] &2an [item] &2!'
  Receiver: '[prefix] &2You got &2, [item] &2from &6[sender]!'
Player:
  PlayerNotFond: '[prefix] &cThe player &6[player] &cwas not found or is not online!'
  PlayerNoInventorySpace: '[prefix] &6[player] &chas no free space in his inventory!'
Help:
  CGUI: '&8''''&b/commandgui &8| &b/cgui&8'''' &eOpen the default GUI &7(&r[gui]&7)&e.'
  Help: '&8''''&b/commandguihelp&8'''' &eOpen this help.'
  Info: '&8''''&b/commandguiadmin info&8'''' &eCall the info from &4Command&9GUI &e.'
  Open: '&8''''&b/commandgui [gui]&8'''' &eOpen the GUI: &6[guiname]&e.'
  Give: '&8''''&b/commandguiadmin give &7<player>&8'''' &eGive a player the GUI item.'
  CreateDefaultGUI: '&8''''&b/commandguiadmin createdefaultgui&8'''' &eCreate a default
    GUI &7([directory])&e.'
  Reload: '&8''''&b/commandguiadmin reload&8'''' &eReload the plugin.'
  UseItem_On: '&8''''&b/gui-item on&8'''' &eActivate the GUIItem for you.'
  UseItem_Off: '&8''''&b/gui-item off&8'''' &eDisable the GUIItem for yourself.'
  UseItem_Slot: '&8''''&b/gui-item slot [slot]&8'''' &eSet the slot for GUIItem for
    you.'
