Plugin:
  VaultNotSetUp: '[prefix] &4Vault / Economy nicht eingerichtet!'
  SoundNotFound: '[prefix] &4Der Sound &6[sound] &4wurde nicht gefunden! Bitte [ue]berpr[ue]fe
    die Einstellungen.'
  OnlyForPlayer: '[prefix] &cDieser Command ist nur f[ue]r Spieler!'
  DefaultGUI:
    create: '[prefix] &2DefaultGUI wurde erstellt. Du findst sie im Verzeichnis: &e[directory]&2!'
  Reload:
    Start: '[prefix] &6Plugin wird neu geladen...'
    End: '[prefix] &2Plugin wurde erfolgreich neu geladen.'
    Warning: '[prefix] &6Um Alias-Befehle zu aktivieren / deaktivieren, lade / starte
      den Server neu!!'
NoPermission:
  ForCommandGUI: '[prefix] &cDu hast keine Permission f[ue]r &4Command&9GUI&c!'
  ForCommand: '[prefix] &cF[ue]r &b[cmd] &cfehlt dir die Permission &6[perm]&c!'
  ForUseItem: '[prefix] &cDir fehlt die Permission &6[perm] &cum das Item f[ue]r die
    GUI: &6[gui] &cnutzen zu k[oe]nnen.'
  ForItem: '[prefix] &cF[ue]r &b[item] &cfehlt dir die Permission &6[perm]&c!'
UseItem:
  UseItem_ON: '[prefix] &2Du hast das GUI-Item aktiviert.'
  UseItem_OFF: '[prefix] &2Du hast das GUI-Item deaktiviert.'
  Change_Slot: '[prefix] &2Du hast das GUI-Item auf Slot &6[slot] &2umgestellt.'
  SlotNotEmpty: '[prefix] &6Der Slot §e[slot] §6ist derzeit belegt!.'
  SlotAlreadySet: '[prefix] &6Der Slot §e[slot] §6ist bereits eingestellt!'
  ItemSlot_wrongValue: '[prefix] &cDer angegebene Slot muss sich zwischen 1 und 9
    befinden!'
Cost:
  Buy_msg: '[prefix] &2Du hast dir [itemname] &2f[ue]r &6[price] &2gekauft.'
  No_money: '[prefix] &cDu hast nicht gen[ue]gend Geld!'
  NoInventorySpace: '[prefix] &cDu hast keinen Platz in deinem Inventar!'
ServerChange:
  onServerChange: '[prefix] &2Du wirst auf den Server §e[server] §2verbunden.'
GUI:
  GUInotFound: '[prefix] &cDie von die gew[ae]hlte GUI gibt es nicht.'
  GUIisDisabled: '[prefix] &cDie GUI [gui] &cist derzeit Deaktiviert!'
Give:
  Sender: '[prefix] &2Du hast &6[player] &2ein [item] &2gegeben!'
  Receiver: '[prefix] &2Du hast von &6[sender] &2, [item] &2bekommen!'
Player:
  PlayerNotFond: '[prefix] &cDer Spieler &6[player] &cwurde nicht gefunden oder ist
    nicht Online!'
  PlayerNoInventorySpace: '[prefix] &6[player] &chat keinen freien Platz in seinem
    Inventar!'
Help:
  CGUI: '&8''''&b/commandgui &8| &b/cgui&8'''' &e[OE]ffne die default GUI &7(&r[gui]&7)&e.'
  Help: '&8''''&b/commandguihelp&8'''' &e[OE]ffne diese help.'
  Info: '&8''''&b/commandguiadmin info&8'''' &eRufe die Infos von &4Command&9GUI &eauf.'
  Open: '&8''''&b/commandgui [gui]&8'''' &e[OE]ffne die GUI: &6[guiname]&e.'
  Give: '&8''''&b/commandguiadmin give &7<player>&8'''' &eGebe einem Spieler das GUI-Item.'
  CreateDefaultGUI: '&8''''&b/commandguiadmin createdefaultgui&8'''' &eLasse eine
    default GUI erstellen &7([directory])&e.'
  Reload: '&8''''&b/commandguiadmin reload&8'''' &eLade das Plugin neu.'
  UseItem_On: '&8''''&b/gui-item on&8'''' &eAktiviere f[ue]r dich das GUIItem.'
  UseItem_Off: '&8''''&b/gui-item off&8'''' &eDeaktiviere f[ue]r dich das GUIItem.'
  UseItem_Slot: '&8''''&b/gui-item slot [slot]&8'''' &eSetze den Slot für GUIItem
    für Sie einstellen.'
